<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title>Mitchell Hillman</title>
		
		<!-- Screen CSS -->
		<link href="interface/css/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />

		<!-- Print CSS -->
		<link href="interface/css/print.css" media="print" rel="stylesheet" type="text/css" />

		<!-- Favicons -->
		<link rel="icon" type="image/ico" href="interface/images/favicon.ico" />
		<link rel="apple-touch-icon-preformatted" href="interface/images/apple-touch-icon.png" />
		
		<!-- Meta -->
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<!--[if IE]>
			<link href="interface/css/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
		<![endif]-->
	</head>
	<body>